@echo off
setlocal EnableExtensions EnableDelayedExpansion
:: =============================================================================
:: WINDOWS CLEANUP SCRIPT
::
:: Purpose:
::   Clears temporary files, application/browser caches, diagnostic data,
::   developer-tool caches, and selected Windows maintenance data.
::
:: Notes:
::   - Executable commands below are preserved exactly from the original file.
::   - Most cleanup commands suppress access-denied/not-found errors with 2>nul.
::   - Some system-level cleanup steps may require an elevated Command Prompt.
::   - Cache files removed by this script may be regenerated by Windows/apps.
:: =============================================================================


:: Record available space before cleanup (bytes) for the final reclaimed-space summary.
for /f "usebackq delims=" %%A in (`powershell -NoProfile -Command "(Get-PSDrive -Name ($env:SystemDrive.TrimEnd(':'))).Free"`) do set "BEFORE_FREE=%%A"

:: Define frequently used cleanup locations once for readability and reuse.
set "TEMP_DIR=%temp%"
set "LOCAL_TEMP=%USERPROFILE%\AppData\Local\Temp"
set "LOCALLOW_TEMP=%USERPROFILE%\AppData\LocalLow\Temp"
set "ROAMING_TEMP=%USERPROFILE%\AppData\Roaming\Temp"
set "WINDOWS_TEMP=C:\Windows\Temp"
set "PREFETCH_DIR=C:\Windows\Prefetch"
set "DOWNLOAD_DIR=%SYSTEMROOT%\SoftwareDistribution\Download"

:: -----------------------------------------------------------------------------
:: TEMPORARY FILES
:: Clear user and Windows temporary directories, then recreate required folders.
:: -----------------------------------------------------------------------------
echo Cleaning up temporary files...
del /s /f /q "%TEMP_DIR%\*.*" 2>nul
rd /s /q "%TEMP_DIR%" 2>nul
mkdir "%TEMP_DIR%" 2>nul

echo Cleaning up Local Temp files...
del /s /f /q "%LOCAL_TEMP%\*.*" 2>nul
rd /s /q "%LOCAL_TEMP%" 2>nul
mkdir "%LOCAL_TEMP%" 2>nul

echo Cleaning up LocalLow Temp files...
del /s /f /q "%LOCALLOW_TEMP%\*.*" 2>nul
rd /s /q "%LOCALLOW_TEMP%" 2>nul
mkdir "%LOCALLOW_TEMP%" 2>nul

if exist "%ROAMING_TEMP%" (
    echo Cleaning up Roaming Temp files...
    del /s /f /q "%ROAMING_TEMP%\*.*" 2>nul
    rd /s /q "%ROAMING_TEMP%" 2>nul
    mkdir "%ROAMING_TEMP%" 2>nul
)

echo Cleaning up Windows Temp files...
del /s /f /q "%WINDOWS_TEMP%\*.*" 2>nul
rd /s /q "%WINDOWS_TEMP%" 2>nul
mkdir "%WINDOWS_TEMP%" 2>nul

:: -----------------------------------------------------------------------------
:: WINDOWS SYSTEM CACHES
:: Remove prefetch data and cached Windows Update downloads, then flush DNS.
:: -----------------------------------------------------------------------------
echo Cleaning up Prefetch files...
del /s /f /q "%PREFETCH_DIR%\*.*" 2>nul

echo Cleaning up Windows Update cache files...
del /s /f /q "%DOWNLOAD_DIR%\*.*" 2>nul

echo Clearing DNS cache...
ipconfig /flushdns

:: -----------------------------------------------------------------------------
:: GENERAL CACHE CLEANUP
:: Clear additional temporary folders and selected GPU/game shader caches.
:: -----------------------------------------------------------------------------
echo Performing additional cleanup tasks...
del /q C:\Temp\*.* 2>nul
del /q C:\Windows\Temp\*.* 2>nul
del /q "%LOCAL_TEMP%\*.*" 2>nul

del /q "%USERPROFILE%\AppData\LocalLow\NVIDIA\PerDriverVersion\DXCache\*.*" 2>nul
del /q "%USERPROFILE%\AppData\Local\AMD\DxCache\*.*" 2>nul
del /q "%USERPROFILE%\AppData\Local\AMD\DxcCache\*.*" 2>nul
del /q "%USERPROFILE%\AppData\Roaming\Arrowhead\Helldivers2\shader_cache\*.*" 2>nul

for /d %%d in (C:\Temp\*) do rd /s /q "%%d" 2>nul
for /d %%d in (C:\Windows\Temp\*) do rd /s /q "%%d" 2>nul
for /d %%d in ("%LOCAL_TEMP%\*") do rd /s /q "%%d" 2>nul
for /d %%d in ("%USERPROFILE%\AppData\LocalLow\NVIDIA\PerDriverVersion\DXCache\*") do rd /s /q "%%d" 2>nul
for /d %%d in ("%USERPROFILE%\AppData\Local\AMD\DxCache\*") do rd /s /q "%%d" 2>nul
for /d %%d in ("%USERPROFILE%\AppData\Local\AMD\DxcCache\*") do rd /s /q "%%d" 2>nul
for /d %%d in ("%USERPROFILE%\AppData\Roaming\Arrowhead\Helldivers2\shader_cache\*") do rd /s /q "%%d" 2>nul

:: Discord: clear the primary application cache.
if exist "%APPDATA%\discord\Cache" (
    echo Cleaning Discord cache...
    del /s /f /q "%APPDATA%\discord\Cache\*.*" 2>nul
    for /d %%d in ("%APPDATA%\discord\Cache\*") do rd /s /q "%%d" 2>nul
)

:: Visual Studio Code: clear Cache, CachedData, and log contents.
if exist "%APPDATA%\Code\Cache" (
    echo Cleaning VS Code Cache...
    del /s /f /q "%APPDATA%\Code\Cache\*.*" 2>nul
    for /d %%d in ("%APPDATA%\Code\Cache\*") do rd /s /q "%%d" 2>nul
)
if exist "%APPDATA%\Code\CachedData" (
    del /s /f /q "%APPDATA%\Code\CachedData\*.*" 2>nul
    for /d %%d in ("%APPDATA%\Code\CachedData\*") do rd /s /q "%%d" 2>nul
)
if exist "%APPDATA%\Code\logs" (
    del /s /f /q "%APPDATA%\Code\logs\*.*" 2>nul
    for /d %%d in ("%APPDATA%\Code\logs\*") do rd /s /q "%%d" 2>nul
)

echo Emptying Recycle Bin...
rd /s /q %systemdrive%\$Recycle.Bin 2>nul

:: -----------------------------------------------------------------------------
:: WINDOWS DIAGNOSTICS AND REPORTING
:: Remove Windows Error Reporting data from user and system report locations.
:: -----------------------------------------------------------------------------
echo Cleaning Windows Error Reporting files...
if exist "%LOCALAPPDATA%\Microsoft\Windows\WER" (
    del /s /f /q "%LOCALAPPDATA%\Microsoft\Windows\WER\*.*" 2>nul
    for /d %%d in ("%LOCALAPPDATA%\Microsoft\Windows\WER\*") do rd /s /q "%%d" 2>nul
)
if exist "C:\ProgramData\Microsoft\Windows\WER\ReportArchive" (
    del /s /f /q "C:\ProgramData\Microsoft\Windows\WER\ReportArchive\*.*" 2>nul
    for /d %%d in ("C:\ProgramData\Microsoft\Windows\WER\ReportArchive\*") do rd /s /q "%%d" 2>nul
)
if exist "C:\ProgramData\Microsoft\Windows\WER\ReportQueue" (
    del /s /f /q "C:\ProgramData\Microsoft\Windows\WER\ReportQueue\*.*" 2>nul
    for /d %%d in ("C:\ProgramData\Microsoft\Windows\WER\ReportQueue\*") do rd /s /q "%%d" 2>nul
)

:: Windows crash dumps: remove MEMORY.DMP and files stored under Minidump.
echo Cleaning Windows crash dumps...
del /f /q "C:\Windows\MEMORY.DMP" 2>nul
if exist "C:\Windows\Minidump" (
    del /s /f /q "C:\Windows\Minidump\*.*" 2>nul
    for /d %%d in ("C:\Windows\Minidump\*") do rd /s /q "%%d" 2>nul
)

:: LiveKernelReports: remove kernel and hardware diagnostic dump files.
echo Cleaning LiveKernelReports...
if exist "C:\Windows\LiveKernelReports" (
    del /s /f /q "C:\Windows\LiveKernelReports\*.*" 2>nul
    for /d %%d in ("C:\Windows\LiveKernelReports\*") do rd /s /q "%%d" 2>nul
)

:: Delivery Optimization: clear cached Windows delivery content.
echo Cleaning Delivery Optimization cache...
if exist "C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Microsoft\Windows\DeliveryOptimization\Cache" (
    del /s /f /q "C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Microsoft\Windows\DeliveryOptimization\Cache\*.*" 2>nul
    for /d %%d in ("C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Microsoft\Windows\DeliveryOptimization\Cache\*") do rd /s /q "%%d" 2>nul
)

:: -----------------------------------------------------------------------------
:: GRAPHICS AND SHADER CACHES
:: Clear DirectX and vendor-specific shader caches that can be regenerated.
:: -----------------------------------------------------------------------------
:: DirectX: clear the per-user D3DS shader cache.
echo Cleaning DirectX shader cache...
if exist "%LOCALAPPDATA%\D3DSCache" (
    del /s /f /q "%LOCALAPPDATA%\D3DSCache\*.*" 2>nul
    for /d %%d in ("%LOCALAPPDATA%\D3DSCache\*") do rd /s /q "%%d" 2>nul
)

:: NVIDIA: clear DXCache, GLCache, and NV_Cache locations.
echo Cleaning NVIDIA shader cache...
if exist "%LOCALAPPDATA%\NVIDIA\DXCache" (
    del /s /f /q "%LOCALAPPDATA%\NVIDIA\DXCache\*.*" 2>nul
    for /d %%d in ("%LOCALAPPDATA%\NVIDIA\DXCache\*") do rd /s /q "%%d" 2>nul
)
if exist "%LOCALAPPDATA%\NVIDIA\GLCache" (
    del /s /f /q "%LOCALAPPDATA%\NVIDIA\GLCache\*.*" 2>nul
    for /d %%d in ("%LOCALAPPDATA%\NVIDIA\GLCache\*") do rd /s /q "%%d" 2>nul
)
if exist "%LOCALAPPDATA%\NVIDIA Corporation\NV_Cache" (
    del /s /f /q "%LOCALAPPDATA%\NVIDIA Corporation\NV_Cache\*.*" 2>nul
    for /d %%d in ("%LOCALAPPDATA%\NVIDIA Corporation\NV_Cache\*") do rd /s /q "%%d" 2>nul
)
if exist "C:\ProgramData\NVIDIA Corporation\NV_Cache" (
    del /s /f /q "C:\ProgramData\NVIDIA Corporation\NV_Cache\*.*" 2>nul
    for /d %%d in ("C:\ProgramData\NVIDIA Corporation\NV_Cache\*") do rd /s /q "%%d" 2>nul
)

:: AMD: clear OpenGL and Vulkan shader cache locations.
echo Cleaning AMD shader cache...
if exist "%LOCALAPPDATA%\AMD\GLCache" (
    del /s /f /q "%LOCALAPPDATA%\AMD\GLCache\*.*" 2>nul
    for /d %%d in ("%LOCALAPPDATA%\AMD\GLCache\*") do rd /s /q "%%d" 2>nul
)
if exist "%LOCALAPPDATA%\AMD\VkCache" (
    del /s /f /q "%LOCALAPPDATA%\AMD\VkCache\*.*" 2>nul
    for /d %%d in ("%LOCALAPPDATA%\AMD\VkCache\*") do rd /s /q "%%d" 2>nul
)

:: Intel: clear the per-user shader cache.
echo Cleaning Intel shader cache...
if exist "%LOCALAPPDATA%\Intel\ShaderCache" (
    del /s /f /q "%LOCALAPPDATA%\Intel\ShaderCache\*.*" 2>nul
    for /d %%d in ("%LOCALAPPDATA%\Intel\ShaderCache\*") do rd /s /q "%%d" 2>nul
)

:: -----------------------------------------------------------------------------
:: WINDOWS EXPLORER AND INTERNET CACHES
:: Clear thumbnail/icon databases and legacy Windows internet cache data.
:: -----------------------------------------------------------------------------
:: Explorer: remove thumbnail and icon cache database files.
echo Cleaning Windows thumbnail cache...
del /f /q "%LOCALAPPDATA%\Microsoft\Windows\Explorer\thumbcache_*.db" 2>nul
del /f /q "%LOCALAPPDATA%\Microsoft\Windows\Explorer\iconcache_*.db" 2>nul

:: Explorer: remove the legacy IconCache.db file when present.
echo Cleaning Windows Explorer icon cache...
if exist "%LOCALAPPDATA%\IconCache.db" (
    del /f /q "%LOCALAPPDATA%\IconCache.db" 2>nul
)

:: Windows internet cache: clear INetCache contents.
echo Cleaning Windows internet cache...
if exist "%LOCALAPPDATA%\Microsoft\Windows\INetCache" (
    del /s /f /q "%LOCALAPPDATA%\Microsoft\Windows\INetCache\*.*" 2>nul
    for /d %%d in ("%LOCALAPPDATA%\Microsoft\Windows\INetCache\*") do rd /s /q "%%d" 2>nul
)

:: -----------------------------------------------------------------------------
:: WEB BROWSER CACHES
:: Clear regenerable browser Cache, Code Cache, and GPUCache data for profiles.
:: -----------------------------------------------------------------------------
:: Microsoft Edge: clear cache data for Default and numbered profiles.
if exist "%LOCALAPPDATA%\Microsoft\Edge\User Data" (
    echo Cleaning Microsoft Edge cache...
    for /d %%p in ("%LOCALAPPDATA%\Microsoft\Edge\User Data\Default" "%LOCALAPPDATA%\Microsoft\Edge\User Data\Profile *") do (
        if exist "%%~p\Cache" (
            del /s /f /q "%%~p\Cache\*.*" 2>nul
            for /d %%d in ("%%~p\Cache\*") do rd /s /q "%%d" 2>nul
        )
        if exist "%%~p\Code Cache" (
            del /s /f /q "%%~p\Code Cache\*.*" 2>nul
            for /d %%d in ("%%~p\Code Cache\*") do rd /s /q "%%d" 2>nul
        )
        if exist "%%~p\GPUCache" (
            del /s /f /q "%%~p\GPUCache\*.*" 2>nul
            for /d %%d in ("%%~p\GPUCache\*") do rd /s /q "%%d" 2>nul
        )
    )
)

:: Google Chrome: clear cache data for Default and numbered profiles.
if exist "%LOCALAPPDATA%\Google\Chrome\User Data" (
    echo Cleaning Google Chrome cache...
    for /d %%p in ("%LOCALAPPDATA%\Google\Chrome\User Data\Default" "%LOCALAPPDATA%\Google\Chrome\User Data\Profile *") do (
        if exist "%%~p\Cache" (
            del /s /f /q "%%~p\Cache\*.*" 2>nul
            for /d %%d in ("%%~p\Cache\*") do rd /s /q "%%d" 2>nul
        )
        if exist "%%~p\Code Cache" (
            del /s /f /q "%%~p\Code Cache\*.*" 2>nul
            for /d %%d in ("%%~p\Code Cache\*") do rd /s /q "%%d" 2>nul
        )
        if exist "%%~p\GPUCache" (
            del /s /f /q "%%~p\GPUCache\*.*" 2>nul
            for /d %%d in ("%%~p\GPUCache\*") do rd /s /q "%%d" 2>nul
        )
    )
)

:: Brave: clear cache data for Default and numbered profiles.
if exist "%LOCALAPPDATA%\BraveSoftware\Brave-Browser\User Data" (
    echo Cleaning Brave cache...
    for /d %%p in ("%LOCALAPPDATA%\BraveSoftware\Brave-Browser\User Data\Default" "%LOCALAPPDATA%\BraveSoftware\Brave-Browser\User Data\Profile *") do (
        if exist "%%~p\Cache" (
            del /s /f /q "%%~p\Cache\*.*" 2>nul
            for /d %%d in ("%%~p\Cache\*") do rd /s /q "%%d" 2>nul
        )
        if exist "%%~p\Code Cache" (
            del /s /f /q "%%~p\Code Cache\*.*" 2>nul
            for /d %%d in ("%%~p\Code Cache\*") do rd /s /q "%%d" 2>nul
        )
        if exist "%%~p\GPUCache" (
            del /s /f /q "%%~p\GPUCache\*.*" 2>nul
            for /d %%d in ("%%~p\GPUCache\*") do rd /s /q "%%d" 2>nul
        )
    )
)

:: Firefox: clear cache2 and startupCache for every local profile.
if exist "%LOCALAPPDATA%\Mozilla\Firefox\Profiles" (
    echo Cleaning Firefox cache...
    for /d %%p in ("%LOCALAPPDATA%\Mozilla\Firefox\Profiles\*") do (
        if exist "%%~p\cache2" (
            del /s /f /q "%%~p\cache2\*.*" 2>nul
            for /d %%d in ("%%~p\cache2\*") do rd /s /q "%%d" 2>nul
        )
        if exist "%%~p\startupCache" (
            del /s /f /q "%%~p\startupCache\*.*" 2>nul
            for /d %%d in ("%%~p\startupCache\*") do rd /s /q "%%d" 2>nul
        )
    )
)

:: -----------------------------------------------------------------------------
:: APPLICATION CACHES
:: Clear regenerable cache data for desktop apps and game launchers.
:: -----------------------------------------------------------------------------
:: Discord: clear Code Cache and GPUCache.
if exist "%APPDATA%\discord\Code Cache" (
    echo Cleaning Discord Code Cache...
    del /s /f /q "%APPDATA%\discord\Code Cache\*.*" 2>nul
    for /d %%d in ("%APPDATA%\discord\Code Cache\*") do rd /s /q "%%d" 2>nul
)
if exist "%APPDATA%\discord\GPUCache" (
    echo Cleaning Discord GPU Cache...
    del /s /f /q "%APPDATA%\discord\GPUCache\*.*" 2>nul
    for /d %%d in ("%APPDATA%\discord\GPUCache\*") do rd /s /q "%%d" 2>nul
)

:: Spotify: clear locally cached Storage contents.
if exist "%LOCALAPPDATA%\Spotify\Storage" (
    echo Cleaning Spotify cache...
    del /s /f /q "%LOCALAPPDATA%\Spotify\Storage\*.*" 2>nul
    for /d %%d in ("%LOCALAPPDATA%\Spotify\Storage\*") do rd /s /q "%%d" 2>nul
)

:: Steam: clear the local HTML cache.
if exist "%LOCALAPPDATA%\Steam\htmlcache" (
    echo Cleaning Steam HTML cache...
    del /s /f /q "%LOCALAPPDATA%\Steam\htmlcache\*.*" 2>nul
    for /d %%d in ("%LOCALAPPDATA%\Steam\htmlcache\*") do rd /s /q "%%d" 2>nul
)

:: Epic Games Launcher: remove matching webcache directories.
if exist "%LOCALAPPDATA%\EpicGamesLauncher\Saved" (
    echo Cleaning Epic Games Launcher cache...
    for /d %%d in ("%LOCALAPPDATA%\EpicGamesLauncher\Saved\webcache*") do rd /s /q "%%d" 2>nul
)

:: Battle.net: clear cached setup data when present.
if exist "%ProgramData%\Battle.net" (
    echo Cleaning Battle.net cache...
    if exist "%ProgramData%\Battle.net\Setup" (
        del /s /f /q "%ProgramData%\Battle.net\Setup\*.*" 2>nul
        for /d %%d in ("%ProgramData%\Battle.net\Setup\*") do rd /s /q "%%d" 2>nul
    )
)

:: Visual Studio Code: clear GPUCache.
if exist "%APPDATA%\Code\GPUCache" (
    echo Cleaning VS Code GPU Cache...
    del /s /f /q "%APPDATA%\Code\GPUCache\*.*" 2>nul
    for /d %%d in ("%APPDATA%\Code\GPUCache\*") do rd /s /q "%%d" 2>nul
)

:: Visual Studio Code: clear Code Cache.
if exist "%APPDATA%\Code\Code Cache" (
    echo Cleaning VS Code Code Cache...
    del /s /f /q "%APPDATA%\Code\Code Cache\*.*" 2>nul
    for /d %%d in ("%APPDATA%\Code\Code Cache\*") do rd /s /q "%%d" 2>nul
)

:: Visual Studio: clear ComponentModelCache for installed local instances.
if exist "%LOCALAPPDATA%\Microsoft\VisualStudio" (
    echo Cleaning Visual Studio component cache...
    for /d %%v in ("%LOCALAPPDATA%\Microsoft\VisualStudio\*") do (
        if exist "%%~v\ComponentModelCache" (
            del /s /f /q "%%~v\ComponentModelCache\*.*" 2>nul
            for /d %%d in ("%%~v\ComponentModelCache\*") do rd /s /q "%%d" 2>nul
        )
    )
)

:: -----------------------------------------------------------------------------
:: DEVELOPER TOOL CACHES
:: Use installed command-line tools to purge package-manager caches.
:: -----------------------------------------------------------------------------
:: NuGet: clear the HTTP cache when dotnet is available.
echo Cleaning NuGet HTTP cache...
where dotnet >nul 2>&1
if not errorlevel 1 (
    dotnet nuget locals http-cache --clear >nul 2>&1
)

:: npm: force-clean the package cache when npm is available.
echo Cleaning npm cache...
where npm >nul 2>&1
if not errorlevel 1 (
    call npm cache clean --force >nul 2>&1
)

:: pip: purge the Python package cache when Python is available.
echo Cleaning pip cache...
where python >nul 2>&1
if not errorlevel 1 (
    python -m pip cache purge >nul 2>&1
)

:: -----------------------------------------------------------------------------
:: WINDOWS MAINTENANCE
:: Remove old setup/check-disk artifacts, run Disk Cleanup, and service components.
:: -----------------------------------------------------------------------------
:: Windows Setup: clear MoSetup upgrade logs.
echo Cleaning Windows upgrade log files...
if exist "C:\Windows\Logs\MoSetup" (
    del /s /f /q "C:\Windows\Logs\MoSetup\*.*" 2>nul
    for /d %%d in ("C:\Windows\Logs\MoSetup\*") do rd /s /q "%%d" 2>nul
)

:: CHKDSK: remove recovered .CHK files from FOUND.??? directories.
echo Cleaning old CHKDSK files...
del /f /q "%SystemDrive%\FOUND.???\*.CHK" 2>nul


:: Record available space after cleanup (bytes).
for /f "usebackq delims=" %%A in (`powershell -NoProfile -Command "(Get-PSDrive -Name ($env:SystemDrive.TrimEnd(':'))).Free"`) do set "AFTER_FREE=%%A"

:: Calculate reclaimed space and format the result as GB, MB, and bytes.
for /f "usebackq delims=" %%A in (`
  powershell -NoProfile -Command ^
    "$before=[double]'%BEFORE_FREE%'; $after=[double]'%AFTER_FREE%'; $delta=$after-$before; " ^
    "if ($delta -lt 0) { $delta = 0 } ;" ^
    "$gb='{0:N2} GB' -f ($delta/1GB); $mb='{0:N0} MB' -f ($delta/1MB); " ^
    "Write-Output ('Cleared: ' + $gb + ' (' + $mb + ', ' + [string]([math]::Round($delta)) + ' bytes)')"
`) do set "CLEARED_RESULT=%%A"

echo.
echo Cleanup completed!
echo %CLEARED_RESULT%
echo.

pause
